#!/usr/bin/env bash
# Re-bundle all individual cards in dist/ into dist/neumorphic-cards.js
# Each card is wrapped in its own IIFE to isolate top-level declarations.
set -e
cd "$(dirname "$0")"
OUT=dist/neumorphic-cards.js
FILES=(
  dist/datepicker-card.js
  dist/timepicker-card.js
  dist/neumorphic-button-card.js
  dist/neumorphic-slider-card.js
  dist/neumorphic-rotary-slider.js
  dist/neumorphic-container-card.js
  dist/neumorphic-calendar-grid-card.js
  dist/neumorphic-climate-card.js
  dist/neumorphic-media-player-card.js
  dist/neumorphic-clock-card.js
  dist/neumorphic-skin-card.js
)
cat > "$OUT" << 'HDR'
/**
 * Neumorphic Cards — bundled suite
 * https://github.com/dvbit/neumorphic-cards
 * Auto-generated by build.sh — do not edit directly.
 * Edit the individual card files in dist/, then run ./build.sh
 */
HDR
for f in "${FILES[@]}"; do
  name=$(basename "$f")
  [ "$name" = "neumorphic-cards.js" ] && continue
  {
    echo ""
    echo "/* ── $name ── */"
    echo "(function () {"
    cat "$f"
    echo ""
    echo "})();"
  } >> "$OUT"
done
node --check "$OUT" && echo "Bundle OK: $OUT"
